import coffeeImg from "../assets/hero-coffee.png";
import foodImg from "../assets/hero-food.png";
import cosmeticsImg from "../assets/hero-cosmetics.png";
import waterImg from "../assets/hero-water.png";
import img1 from "../assets/1.jpg";
import img2 from "../assets/2.jpg";
import img3 from "../assets/3.jpg";

export interface Product {
  id: string;
  name: string;
  category: string;
  shortDesc: string;
  longDesc: string;
  price: number;
  tags: string[];
  image: string;
  precautions: string[];
  storage: string;
  usage: string;
  rating: number;
  reviews: number;
}

export const productsData: Product[] = [
  // ─── Premium Coffee ───
  {
    id: "1",
    name: "Artisan Dark Roast",
    category: "Premium Coffee",
    shortDesc: "Rich, bold, and perfectly roasted.",
    longDesc: "Experience the intense flavors of our Artisan Dark Roast. Sourced from high-altitude farms, these beans offer a full-bodied cup with notes of dark chocolate and toasted nuts.",
    price: 850,
    tags: ["Dark Roast", "Single Origin", "Bestseller"],
    image: coffeeImg,
    precautions: ["Avoid consumption late at night if sensitive to caffeine."],
    storage: "Store in an airtight container in a cool, dark place.",
    usage: "Use 2 tablespoons of ground coffee per 6 ounces of water.",
    rating: 4.9,
    reviews: 1245,
  },
  {
    id: "2",
    name: "Ethiopian Yirgacheffe",
    category: "Premium Coffee",
    shortDesc: "Light roast with floral notes.",
    longDesc: "A bright and complex light roast featuring sweet floral aromas and a vibrant citrus finish. Perfect for pour-over brewing.",
    price: 1050,
    tags: ["Light Roast", "Fruity", "Premium"],
    image: img1,
    precautions: ["Best consumed freshly ground."],
    storage: "Keep away from moisture and direct sunlight.",
    usage: "Ideal for V60 or Chemex. Brew at 93°C.",
    rating: 4.8,
    reviews: 890,
  },
  {
    id: "3",
    name: "Classic Espresso Blend",
    category: "Premium Coffee",
    shortDesc: "Smooth and balanced for espresso.",
    longDesc: "A carefully crafted blend of Arabica and Robusta beans, designed to produce a rich crema and a balanced, sweet espresso shot.",
    price: 750,
    tags: ["Espresso", "Blend", "Smooth"],
    image: img2,
    precautions: ["Contains high caffeine content."],
    storage: "Store at room temperature in a sealed bag.",
    usage: "Grind fine for espresso machines. Dose 18g for a double shot.",
    rating: 4.7,
    reviews: 2100,
  },
  {
    id: "4",
    name: "Cold Brew Reserve",
    category: "Premium Coffee",
    shortDesc: "Specially roasted for cold brewing.",
    longDesc: "Coarse ground beans that deliver a incredibly smooth, low-acidity cold brew with natural caramel sweetness.",
    price: 900,
    tags: ["Cold Brew", "Low Acidity"],
    image: img3,
    precautions: ["Consume within 7 days after brewing."],
    storage: "Store whole beans in a cool pantry.",
    usage: "Steep 1 part coffee to 8 parts cold water for 12-24 hours.",
    rating: 4.9,
    reviews: 560,
  },
  {
    id: "5",
    name: "Decaf Colombian",
    category: "Premium Coffee",
    shortDesc: "All the flavor, zero the jitters.",
    longDesc: "Swiss Water processed decaf beans that retain the classic Colombian profile of sweet caramel and mild fruitiness.",
    price: 950,
    tags: ["Decaf", "Swiss Water Process"],
    image: coffeeImg,
    precautions: ["None."],
    storage: "Store in an airtight container.",
    usage: "Brew as you would regular coffee.",
    rating: 4.6,
    reviews: 430,
  },

  // ─── Organic Food ───
  {
    id: "6",
    name: "Farm Fresh Organic Veggie Box",
    category: "Organic Food",
    shortDesc: "Seasonal mix of organic vegetables.",
    longDesc: "A hand-picked selection of the freshest seasonal vegetables straight from local organic farms. Zero pesticides, pure nutrition.",
    price: 1200,
    tags: ["Fresh", "Organic", "Seasonal"],
    image: foodImg,
    precautions: ["Wash thoroughly before consumption."],
    storage: "Keep refrigerated in the crisper drawer.",
    usage: "Ideal for salads, roasting, or daily cooking.",
    rating: 4.8,
    reviews: 3200,
  },
  {
    id: "7",
    name: "Organic Quinoa Superpack",
    category: "Organic Food",
    shortDesc: "High-protein ancient grain.",
    longDesc: "Premium white quinoa packed with protein, fiber, and essential amino acids. A perfect healthy alternative to rice.",
    price: 450,
    tags: ["Gluten Free", "Superfood"],
    image: img1,
    precautions: ["Rinse well before cooking to remove saponins."],
    storage: "Store in a dry, cool place.",
    usage: "Boil 1 cup of quinoa with 2 cups of water for 15 minutes.",
    rating: 4.7,
    reviews: 1540,
  },
  {
    id: "8",
    name: "Wildflower Raw Honey",
    category: "Organic Food",
    shortDesc: "Unprocessed, pure raw honey.",
    longDesc: "Sourced from pristine wildflower meadows. This raw honey is rich in enzymes, antioxidants, and natural sweetness.",
    price: 650,
    tags: ["Raw", "Natural Sweetener"],
    image: img2,
    precautions: ["Do not feed to infants under 1 year of age."],
    storage: "Store at room temperature. Do not refrigerate.",
    usage: "Use as a sweetener in tea, on toast, or in dressings.",
    rating: 4.9,
    reviews: 2800,
  },
  {
    id: "9",
    name: "Organic Extra Virgin Olive Oil",
    category: "Organic Food",
    shortDesc: "Cold-pressed premium olive oil.",
    longDesc: "First cold-pressed from organically grown olives, offering a robust flavor profile perfect for dressings and light cooking.",
    price: 1400,
    tags: ["Cold Pressed", "Heart Healthy"],
    image: img3,
    precautions: ["Avoid heating past its smoke point (190°C)."],
    storage: "Keep in a dark, cool cupboard away from stove heat.",
    usage: "Drizzle over salads, pastas, or use for dipping bread.",
    rating: 4.8,
    reviews: 1120,
  },
  {
    id: "10",
    name: "Sprouted Multi-Grain Bread",
    category: "Organic Food",
    shortDesc: "Nutritious, easily digestible bread.",
    longDesc: "Baked fresh daily using sprouted organic grains. High in fiber and easier to digest than conventional wheat bread.",
    price: 150,
    tags: ["Vegan", "High Fiber"],
    image: foodImg,
    precautions: ["Contains gluten (unless specified gluten-free)."],
    storage: "Store in a bread box or refrigerate for longer shelf life.",
    usage: "Great for sandwiches or morning toast.",
    rating: 4.5,
    reviews: 850,
  },

  // ─── Luxury Cosmetics ───
  {
    id: "11",
    name: "Radiance Vitamin C Serum",
    category: "Luxury Cosmetics",
    shortDesc: "Brighten and even out skin tone.",
    longDesc: "A potent 15% Vitamin C serum formulated to reduce hyperpigmentation, boost collagen, and give your skin a luminous glow.",
    price: 2499,
    tags: ["Brightening", "Anti-Aging"],
    image: cosmeticsImg,
    precautions: ["Always follow up with sunscreen during the day.", "Patch test before full application."],
    storage: "Store in a cool, dark place to prevent oxidation.",
    usage: "Apply 3-4 drops to clean, dry face every morning.",
    rating: 4.8,
    reviews: 4100,
  },
  {
    id: "12",
    name: "Velvet Matte Lipstick",
    category: "Luxury Cosmetics",
    shortDesc: "Long-lasting, intense color.",
    longDesc: "A luxurious matte lipstick that glides on smoothly, delivering highly pigmented color without drying out your lips.",
    price: 1200,
    tags: ["Cruelty Free", "Long Wear"],
    image: img1,
    precautions: ["Avoid ingesting."],
    storage: "Keep cap tightly closed and store at room temperature.",
    usage: "Apply directly to lips. Reapply as needed.",
    rating: 4.7,
    reviews: 1950,
  },
  {
    id: "13",
    name: "Botanical Night Cream",
    category: "Luxury Cosmetics",
    shortDesc: "Intense overnight hydration.",
    longDesc: "Rich, restorative night cream infused with rare botanical extracts to repair the skin barrier while you sleep.",
    price: 3200,
    tags: ["Hydrating", "Vegan"],
    image: img2,
    precautions: ["For external use only.", "Avoid direct contact with eyes."],
    storage: "Store in a cool, dry place.",
    usage: "Massage gently onto face and neck as the last step of your evening routine.",
    rating: 4.9,
    reviews: 850,
  },
  {
    id: "14",
    name: "Silk Finish Foundation",
    category: "Luxury Cosmetics",
    shortDesc: "Flawless, breathable coverage.",
    longDesc: "A lightweight liquid foundation that provides buildable coverage with a natural, skin-like silk finish.",
    price: 2800,
    tags: ["Makeup", "All Skin Types"],
    image: img3,
    precautions: ["Shake well before use."],
    storage: "Keep away from direct sunlight.",
    usage: "Blend onto skin using a sponge or brush.",
    rating: 4.6,
    reviews: 1200,
  },
  {
    id: "15",
    name: "Rosewater Hydrating Mist",
    category: "Luxury Cosmetics",
    shortDesc: "Instant refreshment and toning.",
    longDesc: "Pure distilled rosewater mist to hydrate, tone, and soothe the skin anytime during the day.",
    price: 850,
    tags: ["Toner", "Refreshing"],
    image: cosmeticsImg,
    precautions: ["Avoid spraying directly into eyes."],
    storage: "Can be refrigerated for a cooling effect.",
    usage: "Spritz over face after cleansing or throughout the day.",
    rating: 4.8,
    reviews: 2200,
  },

  // ─── Pure Hydration ───
  {
    id: "16",
    name: "Alkaline Mountain Water",
    category: "Pure Hydration",
    shortDesc: "Perfectly pH balanced hydration.",
    longDesc: "Sourced from pristine mountain springs, this water is naturally alkaline (pH 8.0+) to help neutralize acidity and hydrate effectively.",
    price: 150,
    tags: ["Alkaline", "Mineral Rich"],
    image: waterImg,
    precautions: ["Do not freeze in the bottle."],
    storage: "Store in a cool, dry place away from direct sunlight.",
    usage: "Drink daily for optimal hydration.",
    rating: 4.9,
    reviews: 5200,
  },
  {
    id: "17",
    name: "Sparkling Mineral Water",
    category: "Pure Hydration",
    shortDesc: "Crisp and refreshing bubbles.",
    longDesc: "Natural mineral water carbonated at the source for a crisp, effervescent taste that pairs perfectly with fine dining.",
    price: 200,
    tags: ["Sparkling", "Zero Calories"],
    image: img1,
    precautions: ["Contents under pressure; open carefully."],
    storage: "Store in a cool place. Serve chilled.",
    usage: "Enjoy chilled on its own or as a mixer.",
    rating: 4.8,
    reviews: 3400,
  },
  {
    id: "18",
    name: "Electrolyte Recovery Water",
    category: "Pure Hydration",
    shortDesc: "Enhanced for rapid rehydration.",
    longDesc: "Purified water infused with essential electrolytes (sodium, potassium, magnesium) to help you recover faster after a workout.",
    price: 180,
    tags: ["Sports Drink", "Electrolytes"],
    image: img2,
    precautions: ["None."],
    storage: "Refrigerate after opening.",
    usage: "Best consumed during or after physical activity.",
    rating: 4.7,
    reviews: 2100,
  },
  {
    id: "19",
    name: "Artesian Spring Water",
    category: "Pure Hydration",
    shortDesc: "Untouched, pure artesian water.",
    longDesc: "Drawn from a deep, protected aquifer. Known for its incredibly smooth taste and soft mouthfeel.",
    price: 250,
    tags: ["Artesian", "Premium"],
    image: img3,
    precautions: ["None."],
    storage: "Store away from strong odors and sunlight.",
    usage: "Drink daily.",
    rating: 4.9,
    reviews: 1890,
  },
  {
    id: "20",
    name: "Vitamin Enhanced Water",
    category: "Pure Hydration",
    shortDesc: "Hydration with a boost of vitamins.",
    longDesc: "Lightly fruit-flavored water fortified with B-vitamins and Vitamin C for a healthy energy boost without the sugar crash.",
    price: 220,
    tags: ["Vitamin C", "Low Sugar"],
    image: waterImg,
    precautions: ["Contains minimal natural sugars."],
    storage: "Keep refrigerated for best taste.",
    usage: "Enjoy chilled anytime.",
    rating: 4.6,
    reviews: 1450,
  }
];
